/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "httprequest.h"
/* Header for class com_bingdu_cy_jnidemo_Hello */

#ifndef _Included_com_bingdu_cy_jnidemo_Hello
#define _Included_com_bingdu_cy_jnidemo_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bingdu_cy_jnidemo_Hello
 * Method:    JniCurl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bingdu_cy_jnidemo_Hello_hello
  (JNIEnv *, jclass);

/*
 * Class:     com_bingdu_cy_jnidemo_Hello
 * Method:    add
 * Signature: (II)I
 */

JNIEXPORT void JNICALL Java_com_bingdu_cy_jnidemo_Hello_download
        (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
